[package]
name = "lox-parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lox-ir = { path = "../lox-ir" }
lox-lex = { path = "../lox-lex" }
salsa = { path = "../salsa" }
