[package]
name = "lox-ir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eq-float = "0.1.0"
salsa = { path="../salsa" }
tracing = "0.1.37"
